### ISSUE TITLE
Class Kubernetes\App\Project\AbstractProject located in ./vendor/kubernetes/php-client/src/App/AbstractProject.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

### ISSUE THREAD

**Issue by rdeenik** [allansun/kubernetes-php-client#13]
AbstractProject.php generates a PSR-4 autoloading error. This is due to the namespace being `namespace Kubernetes\App\Project` and `AbstractProject.php` sitting in directory `App`. Can the namespace be should to `namespace Kubernetes\App`, however I'm not sure if this would result in unintentional consequences.

**Comment by allansun** [comment]
@rdeenik sorry about this late reply.

You are absolutely right! The bug is fixed and will be reflected in future auto generated codes.

I created the App namespace purely as a demonstration to show how this lib can be used. In fact it was not supposed to be in the generated code at all... You can copy the whole directory into your own project (change to proper namespace of course).  In my work I put it into a Symfony project to work with console command.
